project:
  type: website
  output-dir: docs
  
website:
  title: "EJ's Attempt at Making a Website Using R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://efishj2.github.io/improved-palm-tree/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

